tool:
  oss:
    aliyun-access-key:
    aliyun-access-key-secret:
    aliyun-bucket-name: 1111111jvjvb
    aliyun-endpoint: oss-cn-beijing.aliyuncs.com
    aliyun-file-url: 1111111jvjvb.oss-cn-beijing.aliyuncs.com
    qiniu-bucket-name: dabaoyingshi
    qiniu-access-key: EQSTit4nxmAmnN-uGiufJXVrGb1F8FzAym89lrsI
    qiniu-base-path: https://images.dabaotv.cn
    qiniu-secret-key: simNyXeM2QaxmIU97549RMNat1dNU4uF2WoizkgA